"""
DP Signal Models & Configuration

Dataclass for divergence signals and proven-edge config constants.
Extracted from dp_divergence_checker.py for modularity.
"""

from typing import Optional
from dataclasses import dataclass


@dataclass
class DPDivergenceSignal:
    """A signal generated by DP divergence analysis"""
    symbol: str
    direction: str  # LONG or SHORT
    signal_type: str  # DP_CONFLUENCE, OPTIONS_DIVERGENCE
    confidence: float
    entry_price: float
    stop_pct: float
    target_pct: float
    reasoning: str
    dp_bias: str  # BULLISH or BEARISH
    options_bias: Optional[str] = None  # For divergence signals
    dp_strength: float = 0.0
    has_divergence: bool = False


# Configuration based on proven data (372 interactions, Dec 5-24 2025)
DP_SIGNAL_CONFIG = {
    # Proven edge: 89.8% WR means we only need 0.11 R/R to profit
    'stop_pct': 0.25,            # Stop loss
    'target_pct': 0.15,          # Take profit (R/R = 0.6, well above 0.11 breakeven)
    'min_dp_volume': 500_000,    # Minimum DP level volume
    'max_distance_pct': 0.3,     # Max distance from price to level (%)
    'min_divergence_strength': 0.55,  # Min strength for divergence signals
    # Divergence-specific
    'divergence_stop_pct': 0.30,      # Wider stop for divergence trades
    'divergence_target_pct': 0.45,    # Higher target (2:1.5 R/R)
}
